/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationStatusRouteImport } from './routes/application-status'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotAppPasswordRouteImport } from './routes/forgot-app-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationGalleryRouteImport } from './routes/notification-gallery'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetAppPasswordRouteImport } from './routes/reset-app-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SchoolApplicationRouteImport } from './routes/school-application'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCarryoversRouteImport } from './routes/admin.carryovers'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminExaminationsRouteImport } from './routes/admin.examinations'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminLevelsRouteImport } from './routes/admin.levels'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOfficersRouteImport } from './routes/admin.officers'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminSemestersRouteImport } from './routes/admin.semesters'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStructureRouteImport } from './routes/admin.structure'
import { Route as AdminStudentImportRouteImport } from './routes/admin.student-import'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerApprovalsRouteImport } from './routes/officer.approvals'
import { Route as OfficerAuditLogsRouteImport } from './routes/officer.audit-logs'
import { Route as OfficerCarryoversRouteImport } from './routes/officer.carryovers'
import { Route as OfficerIntegrityRouteImport } from './routes/officer.integrity'
import { Route as OfficerLiveMonitorRouteImport } from './routes/officer.live-monitor'
import { Route as OfficerNotificationsRouteImport } from './routes/officer.notifications'
import { Route as OfficerPostToStudentsRouteImport } from './routes/officer.post-to-students'
import { Route as OfficerProfileRouteImport } from './routes/officer.profile'
import { Route as OfficerReportsRouteImport } from './routes/officer.reports'
import { Route as OfficerResultsRouteImport } from './routes/officer.results'
import { Route as OfficerSettingsRouteImport } from './routes/officer.settings'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentContactOfficerRouteImport } from './routes/student.contact-officer'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentExaminationsRouteImport } from './routes/student.examinations'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminApplicationsRouteImport } from './routes/super-admin.applications'
import { Route as SuperAdminAuditLogsRouteImport } from './routes/super-admin.audit-logs'
import { Route as SuperAdminExaminationsRouteImport } from './routes/super-admin.examinations'
import { Route as SuperAdminMessagesRouteImport } from './routes/super-admin.messages'
import { Route as SuperAdminNotificationsRouteImport } from './routes/super-admin.notifications'
import { Route as SuperAdminProfileRouteImport } from './routes/super-admin.profile'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin.schools'
import { Route as SuperAdminServicesRouteImport } from './routes/super-admin.services'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSubscriptionsRouteImport } from './routes/super-admin.subscriptions'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherCoursesRouteImport } from './routes/teacher.courses'
import { Route as TeacherExamSecurityRouteImport } from './routes/teacher.exam-security'
import { Route as TeacherExaminationsRouteImport } from './routes/teacher.examinations'
import { Route as TeacherIntegrityRouteImport } from './routes/teacher.integrity'
import { Route as TeacherLiveExamsRouteImport } from './routes/teacher.live-exams'
import { Route as TeacherMarkingRouteImport } from './routes/teacher.marking'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherQuestionBankRouteImport } from './routes/teacher.question-bank'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherSubmissionsRouteImport } from './routes/teacher.submissions'
import { Route as AdminStudentIdRouteImport } from './routes/admin.student.$id'
import { Route as OfficerExamPreviewIdRouteImport } from './routes/officer.exam-preview.$id'
import { Route as StudentExamIdRouteImport } from './routes/student.exam.$id'
import { Route as StudentMessagesConversationIdRouteImport } from './routes/student.messages.$conversationId'
import { Route as StudentResultsIdRouteImport } from './routes/student.results.$id'
import { Route as StudentUserUserIdRouteImport } from './routes/student.user.$userId'
import { Route as SuperAdminSchoolsIndexRouteImport } from './routes/super-admin.schools.index'
import { Route as SuperAdminSchoolsIdRouteImport } from './routes/super-admin.schools.$id'
import { Route as TeacherExamPaperIdRouteImport } from './routes/teacher.exam-paper.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationStatusRoute = ApplicationStatusRouteImport.update({
  id: '/application-status',
  path: '/application-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotAppPasswordRoute = ForgotAppPasswordRouteImport.update({
  id: '/forgot-app-password',
  path: '/forgot-app-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationGalleryRoute = NotificationGalleryRouteImport.update({
  id: '/notification-gallery',
  path: '/notification-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetAppPasswordRoute = ResetAppPasswordRouteImport.update({
  id: '/reset-app-password',
  path: '/reset-app-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolApplicationRoute = SchoolApplicationRouteImport.update({
  id: '/school-application',
  path: '/school-application',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarryoversRoute = AdminCarryoversRouteImport.update({
  id: '/carryovers',
  path: '/carryovers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExaminationsRoute = AdminExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLevelsRoute = AdminLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficersRoute = AdminOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSemestersRoute = AdminSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStructureRoute = AdminStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentImportRoute = AdminStudentImportRouteImport.update({
  id: '/student-import',
  path: '/student-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerApprovalsRoute = OfficerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerAuditLogsRoute = OfficerAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerCarryoversRoute = OfficerCarryoversRouteImport.update({
  id: '/carryovers',
  path: '/carryovers',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerIntegrityRoute = OfficerIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerLiveMonitorRoute = OfficerLiveMonitorRouteImport.update({
  id: '/live-monitor',
  path: '/live-monitor',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerNotificationsRoute = OfficerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerPostToStudentsRoute = OfficerPostToStudentsRouteImport.update({
  id: '/post-to-students',
  path: '/post-to-students',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerProfileRoute = OfficerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerResultsRoute = OfficerResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerSettingsRoute = OfficerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OfficerRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentContactOfficerRoute = StudentContactOfficerRouteImport.update({
  id: '/contact-officer',
  path: '/contact-officer',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExaminationsRoute = StudentExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminApplicationsRoute = SuperAdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAuditLogsRoute = SuperAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminExaminationsRoute = SuperAdminExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminMessagesRoute = SuperAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminNotificationsRoute = SuperAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminProfileRoute = SuperAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminServicesRoute = SuperAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSubscriptionsRoute = SuperAdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamSecurityRoute = TeacherExamSecurityRouteImport.update({
  id: '/exam-security',
  path: '/exam-security',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExaminationsRoute = TeacherExaminationsRouteImport.update({
  id: '/examinations',
  path: '/examinations',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherIntegrityRoute = TeacherIntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveExamsRoute = TeacherLiveExamsRouteImport.update({
  id: '/live-exams',
  path: '/live-exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMarkingRoute = TeacherMarkingRouteImport.update({
  id: '/marking',
  path: '/marking',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuestionBankRoute = TeacherQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSubmissionsRoute = TeacherSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminStudentIdRoute = AdminStudentIdRouteImport.update({
  id: '/student/$id',
  path: '/student/$id',
  getParentRoute: () => AdminRoute,
} as any)
const OfficerExamPreviewIdRoute = OfficerExamPreviewIdRouteImport.update({
  id: '/exam-preview/$id',
  path: '/exam-preview/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const StudentExamIdRoute = StudentExamIdRouteImport.update({
  id: '/exam/$id',
  path: '/exam/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesConversationIdRoute =
  StudentMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => StudentMessagesRoute,
  } as any)
const StudentResultsIdRoute = StudentResultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentResultsRoute,
} as any)
const StudentUserUserIdRoute = StudentUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => StudentRoute,
} as any)
const SuperAdminSchoolsIndexRoute = SuperAdminSchoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminSchoolsRoute,
} as any)
const SuperAdminSchoolsIdRoute = SuperAdminSchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuperAdminSchoolsRoute,
} as any)
const TeacherExamPaperIdRoute = TeacherExamPaperIdRouteImport.update({
  id: '/exam-paper/$id',
  path: '/exam-paper/$id',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/features': typeof FeaturesRoute
  '/forgot-app-password': typeof ForgotAppPasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notification-gallery': typeof NotificationGalleryRoute
  '/officer': typeof OfficerRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-app-password': typeof ResetAppPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-application': typeof SchoolApplicationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/carryovers': typeof AdminCarryoversRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/examinations': typeof AdminExaminationsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/semesters': typeof AdminSemestersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/student-import': typeof AdminStudentImportRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/officer/approvals': typeof OfficerApprovalsRoute
  '/officer/audit-logs': typeof OfficerAuditLogsRoute
  '/officer/carryovers': typeof OfficerCarryoversRoute
  '/officer/integrity': typeof OfficerIntegrityRoute
  '/officer/live-monitor': typeof OfficerLiveMonitorRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/post-to-students': typeof OfficerPostToStudentsRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/results': typeof OfficerResultsRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/student/contact-officer': typeof StudentContactOfficerRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/examinations': typeof StudentExaminationsRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/messages': typeof StudentMessagesRouteWithChildren
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/examinations': typeof SuperAdminExaminationsRoute
  '/super-admin/messages': typeof SuperAdminMessagesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/services': typeof SuperAdminServicesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/exam-security': typeof TeacherExamSecurityRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/integrity': typeof TeacherIntegrityRoute
  '/teacher/live-exams': typeof TeacherLiveExamsRoute
  '/teacher/marking': typeof TeacherMarkingRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/student/$id': typeof AdminStudentIdRoute
  '/officer/exam-preview/$id': typeof OfficerExamPreviewIdRoute
  '/student/exam/$id': typeof StudentExamIdRoute
  '/student/messages/$conversationId': typeof StudentMessagesConversationIdRoute
  '/student/results/$id': typeof StudentResultsIdRoute
  '/student/user/$userId': typeof StudentUserUserIdRoute
  '/super-admin/schools/$id': typeof SuperAdminSchoolsIdRoute
  '/teacher/exam-paper/$id': typeof TeacherExamPaperIdRoute
  '/super-admin/schools/': typeof SuperAdminSchoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-status': typeof ApplicationStatusRoute
  '/features': typeof FeaturesRoute
  '/forgot-app-password': typeof ForgotAppPasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notification-gallery': typeof NotificationGalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-app-password': typeof ResetAppPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-application': typeof SchoolApplicationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/admin/carryovers': typeof AdminCarryoversRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/examinations': typeof AdminExaminationsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/semesters': typeof AdminSemestersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/student-import': typeof AdminStudentImportRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/officer/approvals': typeof OfficerApprovalsRoute
  '/officer/audit-logs': typeof OfficerAuditLogsRoute
  '/officer/carryovers': typeof OfficerCarryoversRoute
  '/officer/integrity': typeof OfficerIntegrityRoute
  '/officer/live-monitor': typeof OfficerLiveMonitorRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/post-to-students': typeof OfficerPostToStudentsRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/results': typeof OfficerResultsRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/student/contact-officer': typeof StudentContactOfficerRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/examinations': typeof StudentExaminationsRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/messages': typeof StudentMessagesRouteWithChildren
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/examinations': typeof SuperAdminExaminationsRoute
  '/super-admin/messages': typeof SuperAdminMessagesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/services': typeof SuperAdminServicesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/exam-security': typeof TeacherExamSecurityRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/integrity': typeof TeacherIntegrityRoute
  '/teacher/live-exams': typeof TeacherLiveExamsRoute
  '/teacher/marking': typeof TeacherMarkingRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/admin': typeof AdminIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/student': typeof StudentIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/student/$id': typeof AdminStudentIdRoute
  '/officer/exam-preview/$id': typeof OfficerExamPreviewIdRoute
  '/student/exam/$id': typeof StudentExamIdRoute
  '/student/messages/$conversationId': typeof StudentMessagesConversationIdRoute
  '/student/results/$id': typeof StudentResultsIdRoute
  '/student/user/$userId': typeof StudentUserUserIdRoute
  '/super-admin/schools/$id': typeof SuperAdminSchoolsIdRoute
  '/teacher/exam-paper/$id': typeof TeacherExamPaperIdRoute
  '/super-admin/schools': typeof SuperAdminSchoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/application-status': typeof ApplicationStatusRoute
  '/features': typeof FeaturesRoute
  '/forgot-app-password': typeof ForgotAppPasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notification-gallery': typeof NotificationGalleryRoute
  '/officer': typeof OfficerRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-app-password': typeof ResetAppPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-application': typeof SchoolApplicationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/carryovers': typeof AdminCarryoversRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/examinations': typeof AdminExaminationsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/levels': typeof AdminLevelsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/semesters': typeof AdminSemestersRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/student-import': typeof AdminStudentImportRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/officer/approvals': typeof OfficerApprovalsRoute
  '/officer/audit-logs': typeof OfficerAuditLogsRoute
  '/officer/carryovers': typeof OfficerCarryoversRoute
  '/officer/integrity': typeof OfficerIntegrityRoute
  '/officer/live-monitor': typeof OfficerLiveMonitorRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/post-to-students': typeof OfficerPostToStudentsRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/results': typeof OfficerResultsRoute
  '/officer/settings': typeof OfficerSettingsRoute
  '/student/contact-officer': typeof StudentContactOfficerRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/examinations': typeof StudentExaminationsRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/messages': typeof StudentMessagesRouteWithChildren
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/results': typeof StudentResultsRouteWithChildren
  '/student/settings': typeof StudentSettingsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/examinations': typeof SuperAdminExaminationsRoute
  '/super-admin/messages': typeof SuperAdminMessagesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRouteWithChildren
  '/super-admin/services': typeof SuperAdminServicesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/teacher/courses': typeof TeacherCoursesRoute
  '/teacher/exam-security': typeof TeacherExamSecurityRoute
  '/teacher/examinations': typeof TeacherExaminationsRoute
  '/teacher/integrity': typeof TeacherIntegrityRoute
  '/teacher/live-exams': typeof TeacherLiveExamsRoute
  '/teacher/marking': typeof TeacherMarkingRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/student/$id': typeof AdminStudentIdRoute
  '/officer/exam-preview/$id': typeof OfficerExamPreviewIdRoute
  '/student/exam/$id': typeof StudentExamIdRoute
  '/student/messages/$conversationId': typeof StudentMessagesConversationIdRoute
  '/student/results/$id': typeof StudentResultsIdRoute
  '/student/user/$userId': typeof StudentUserUserIdRoute
  '/super-admin/schools/$id': typeof SuperAdminSchoolsIdRoute
  '/teacher/exam-paper/$id': typeof TeacherExamPaperIdRoute
  '/super-admin/schools/': typeof SuperAdminSchoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/application-status'
    | '/features'
    | '/forgot-app-password'
    | '/forgot-password'
    | '/login'
    | '/notification-gallery'
    | '/officer'
    | '/pricing'
    | '/privacy'
    | '/reset-app-password'
    | '/reset-password'
    | '/school-application'
    | '/sitemap.xml'
    | '/student'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/admin/carryovers'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/examinations'
    | '/admin/faculties'
    | '/admin/levels'
    | '/admin/notifications'
    | '/admin/officers'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/semesters'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/structure'
    | '/admin/student-import'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/callback'
    | '/officer/approvals'
    | '/officer/audit-logs'
    | '/officer/carryovers'
    | '/officer/integrity'
    | '/officer/live-monitor'
    | '/officer/notifications'
    | '/officer/post-to-students'
    | '/officer/profile'
    | '/officer/reports'
    | '/officer/results'
    | '/officer/settings'
    | '/student/contact-officer'
    | '/student/courses'
    | '/student/examinations'
    | '/student/history'
    | '/student/materials'
    | '/student/messages'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/student/settings'
    | '/super-admin/applications'
    | '/super-admin/audit-logs'
    | '/super-admin/examinations'
    | '/super-admin/messages'
    | '/super-admin/notifications'
    | '/super-admin/profile'
    | '/super-admin/reports'
    | '/super-admin/schools'
    | '/super-admin/services'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/users'
    | '/teacher/courses'
    | '/teacher/exam-security'
    | '/teacher/examinations'
    | '/teacher/integrity'
    | '/teacher/live-exams'
    | '/teacher/marking'
    | '/teacher/materials'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/results'
    | '/teacher/settings'
    | '/teacher/submissions'
    | '/admin/'
    | '/officer/'
    | '/student/'
    | '/super-admin/'
    | '/teacher/'
    | '/admin/student/$id'
    | '/officer/exam-preview/$id'
    | '/student/exam/$id'
    | '/student/messages/$conversationId'
    | '/student/results/$id'
    | '/student/user/$userId'
    | '/super-admin/schools/$id'
    | '/teacher/exam-paper/$id'
    | '/super-admin/schools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application-status'
    | '/features'
    | '/forgot-app-password'
    | '/forgot-password'
    | '/login'
    | '/notification-gallery'
    | '/pricing'
    | '/privacy'
    | '/reset-app-password'
    | '/reset-password'
    | '/school-application'
    | '/sitemap.xml'
    | '/support'
    | '/admin/carryovers'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/examinations'
    | '/admin/faculties'
    | '/admin/levels'
    | '/admin/notifications'
    | '/admin/officers'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/semesters'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/structure'
    | '/admin/student-import'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/callback'
    | '/officer/approvals'
    | '/officer/audit-logs'
    | '/officer/carryovers'
    | '/officer/integrity'
    | '/officer/live-monitor'
    | '/officer/notifications'
    | '/officer/post-to-students'
    | '/officer/profile'
    | '/officer/reports'
    | '/officer/results'
    | '/officer/settings'
    | '/student/contact-officer'
    | '/student/courses'
    | '/student/examinations'
    | '/student/history'
    | '/student/materials'
    | '/student/messages'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/student/settings'
    | '/super-admin/applications'
    | '/super-admin/audit-logs'
    | '/super-admin/examinations'
    | '/super-admin/messages'
    | '/super-admin/notifications'
    | '/super-admin/profile'
    | '/super-admin/reports'
    | '/super-admin/services'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/users'
    | '/teacher/courses'
    | '/teacher/exam-security'
    | '/teacher/examinations'
    | '/teacher/integrity'
    | '/teacher/live-exams'
    | '/teacher/marking'
    | '/teacher/materials'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/results'
    | '/teacher/settings'
    | '/teacher/submissions'
    | '/admin'
    | '/officer'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/admin/student/$id'
    | '/officer/exam-preview/$id'
    | '/student/exam/$id'
    | '/student/messages/$conversationId'
    | '/student/results/$id'
    | '/student/user/$userId'
    | '/super-admin/schools/$id'
    | '/teacher/exam-paper/$id'
    | '/super-admin/schools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/application-status'
    | '/features'
    | '/forgot-app-password'
    | '/forgot-password'
    | '/login'
    | '/notification-gallery'
    | '/officer'
    | '/pricing'
    | '/privacy'
    | '/reset-app-password'
    | '/reset-password'
    | '/school-application'
    | '/sitemap.xml'
    | '/student'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/admin/carryovers'
    | '/admin/courses'
    | '/admin/departments'
    | '/admin/examinations'
    | '/admin/faculties'
    | '/admin/levels'
    | '/admin/notifications'
    | '/admin/officers'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/semesters'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/structure'
    | '/admin/student-import'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/auth/callback'
    | '/officer/approvals'
    | '/officer/audit-logs'
    | '/officer/carryovers'
    | '/officer/integrity'
    | '/officer/live-monitor'
    | '/officer/notifications'
    | '/officer/post-to-students'
    | '/officer/profile'
    | '/officer/reports'
    | '/officer/results'
    | '/officer/settings'
    | '/student/contact-officer'
    | '/student/courses'
    | '/student/examinations'
    | '/student/history'
    | '/student/materials'
    | '/student/messages'
    | '/student/notifications'
    | '/student/profile'
    | '/student/results'
    | '/student/settings'
    | '/super-admin/applications'
    | '/super-admin/audit-logs'
    | '/super-admin/examinations'
    | '/super-admin/messages'
    | '/super-admin/notifications'
    | '/super-admin/profile'
    | '/super-admin/reports'
    | '/super-admin/schools'
    | '/super-admin/services'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/users'
    | '/teacher/courses'
    | '/teacher/exam-security'
    | '/teacher/examinations'
    | '/teacher/integrity'
    | '/teacher/live-exams'
    | '/teacher/marking'
    | '/teacher/materials'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/question-bank'
    | '/teacher/results'
    | '/teacher/settings'
    | '/teacher/submissions'
    | '/admin/'
    | '/officer/'
    | '/student/'
    | '/super-admin/'
    | '/teacher/'
    | '/admin/student/$id'
    | '/officer/exam-preview/$id'
    | '/student/exam/$id'
    | '/student/messages/$conversationId'
    | '/student/results/$id'
    | '/student/user/$userId'
    | '/super-admin/schools/$id'
    | '/teacher/exam-paper/$id'
    | '/super-admin/schools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplicationStatusRoute: typeof ApplicationStatusRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotAppPasswordRoute: typeof ForgotAppPasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationGalleryRoute: typeof NotificationGalleryRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetAppPasswordRoute: typeof ResetAppPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolApplicationRoute: typeof SchoolApplicationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SupportRoute: typeof SupportRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-status': {
      id: '/application-status'
      path: '/application-status'
      fullPath: '/application-status'
      preLoaderRoute: typeof ApplicationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-app-password': {
      id: '/forgot-app-password'
      path: '/forgot-app-password'
      fullPath: '/forgot-app-password'
      preLoaderRoute: typeof ForgotAppPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-gallery': {
      id: '/notification-gallery'
      path: '/notification-gallery'
      fullPath: '/notification-gallery'
      preLoaderRoute: typeof NotificationGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-app-password': {
      id: '/reset-app-password'
      path: '/reset-app-password'
      fullPath: '/reset-app-password'
      preLoaderRoute: typeof ResetAppPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-application': {
      id: '/school-application'
      path: '/school-application'
      fullPath: '/school-application'
      preLoaderRoute: typeof SchoolApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carryovers': {
      id: '/admin/carryovers'
      path: '/carryovers'
      fullPath: '/admin/carryovers'
      preLoaderRoute: typeof AdminCarryoversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/examinations': {
      id: '/admin/examinations'
      path: '/examinations'
      fullPath: '/admin/examinations'
      preLoaderRoute: typeof AdminExaminationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/levels': {
      id: '/admin/levels'
      path: '/levels'
      fullPath: '/admin/levels'
      preLoaderRoute: typeof AdminLevelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/officers': {
      id: '/admin/officers'
      path: '/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AdminOfficersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/semesters': {
      id: '/admin/semesters'
      path: '/semesters'
      fullPath: '/admin/semesters'
      preLoaderRoute: typeof AdminSemestersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/structure': {
      id: '/admin/structure'
      path: '/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AdminStructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/student-import': {
      id: '/admin/student-import'
      path: '/student-import'
      fullPath: '/admin/student-import'
      preLoaderRoute: typeof AdminStudentImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/approvals': {
      id: '/officer/approvals'
      path: '/approvals'
      fullPath: '/officer/approvals'
      preLoaderRoute: typeof OfficerApprovalsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/audit-logs': {
      id: '/officer/audit-logs'
      path: '/audit-logs'
      fullPath: '/officer/audit-logs'
      preLoaderRoute: typeof OfficerAuditLogsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/carryovers': {
      id: '/officer/carryovers'
      path: '/carryovers'
      fullPath: '/officer/carryovers'
      preLoaderRoute: typeof OfficerCarryoversRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/integrity': {
      id: '/officer/integrity'
      path: '/integrity'
      fullPath: '/officer/integrity'
      preLoaderRoute: typeof OfficerIntegrityRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/live-monitor': {
      id: '/officer/live-monitor'
      path: '/live-monitor'
      fullPath: '/officer/live-monitor'
      preLoaderRoute: typeof OfficerLiveMonitorRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/notifications': {
      id: '/officer/notifications'
      path: '/notifications'
      fullPath: '/officer/notifications'
      preLoaderRoute: typeof OfficerNotificationsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/post-to-students': {
      id: '/officer/post-to-students'
      path: '/post-to-students'
      fullPath: '/officer/post-to-students'
      preLoaderRoute: typeof OfficerPostToStudentsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/profile': {
      id: '/officer/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerProfileRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/reports': {
      id: '/officer/reports'
      path: '/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/results': {
      id: '/officer/results'
      path: '/results'
      fullPath: '/officer/results'
      preLoaderRoute: typeof OfficerResultsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/settings': {
      id: '/officer/settings'
      path: '/settings'
      fullPath: '/officer/settings'
      preLoaderRoute: typeof OfficerSettingsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/contact-officer': {
      id: '/student/contact-officer'
      path: '/contact-officer'
      fullPath: '/student/contact-officer'
      preLoaderRoute: typeof StudentContactOfficerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/examinations': {
      id: '/student/examinations'
      path: '/examinations'
      fullPath: '/student/examinations'
      preLoaderRoute: typeof StudentExaminationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/applications': {
      id: '/super-admin/applications'
      path: '/applications'
      fullPath: '/super-admin/applications'
      preLoaderRoute: typeof SuperAdminApplicationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/audit-logs': {
      id: '/super-admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof SuperAdminAuditLogsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/examinations': {
      id: '/super-admin/examinations'
      path: '/examinations'
      fullPath: '/super-admin/examinations'
      preLoaderRoute: typeof SuperAdminExaminationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/messages': {
      id: '/super-admin/messages'
      path: '/messages'
      fullPath: '/super-admin/messages'
      preLoaderRoute: typeof SuperAdminMessagesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/notifications': {
      id: '/super-admin/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperAdminNotificationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/profile': {
      id: '/super-admin/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof SuperAdminProfileRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/schools': {
      id: '/super-admin/schools'
      path: '/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof SuperAdminSchoolsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/services': {
      id: '/super-admin/services'
      path: '/services'
      fullPath: '/super-admin/services'
      preLoaderRoute: typeof SuperAdminServicesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/subscriptions': {
      id: '/super-admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperAdminSubscriptionsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exam-security': {
      id: '/teacher/exam-security'
      path: '/exam-security'
      fullPath: '/teacher/exam-security'
      preLoaderRoute: typeof TeacherExamSecurityRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/examinations': {
      id: '/teacher/examinations'
      path: '/examinations'
      fullPath: '/teacher/examinations'
      preLoaderRoute: typeof TeacherExaminationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/integrity': {
      id: '/teacher/integrity'
      path: '/integrity'
      fullPath: '/teacher/integrity'
      preLoaderRoute: typeof TeacherIntegrityRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live-exams': {
      id: '/teacher/live-exams'
      path: '/live-exams'
      fullPath: '/teacher/live-exams'
      preLoaderRoute: typeof TeacherLiveExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/marking': {
      id: '/teacher/marking'
      path: '/marking'
      fullPath: '/teacher/marking'
      preLoaderRoute: typeof TeacherMarkingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/materials': {
      id: '/teacher/materials'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/question-bank': {
      id: '/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/teacher/question-bank'
      preLoaderRoute: typeof TeacherQuestionBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/submissions': {
      id: '/teacher/submissions'
      path: '/submissions'
      fullPath: '/teacher/submissions'
      preLoaderRoute: typeof TeacherSubmissionsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/student/$id': {
      id: '/admin/student/$id'
      path: '/student/$id'
      fullPath: '/admin/student/$id'
      preLoaderRoute: typeof AdminStudentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/officer/exam-preview/$id': {
      id: '/officer/exam-preview/$id'
      path: '/exam-preview/$id'
      fullPath: '/officer/exam-preview/$id'
      preLoaderRoute: typeof OfficerExamPreviewIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/student/exam/$id': {
      id: '/student/exam/$id'
      path: '/exam/$id'
      fullPath: '/student/exam/$id'
      preLoaderRoute: typeof StudentExamIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages/$conversationId': {
      id: '/student/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/student/messages/$conversationId'
      preLoaderRoute: typeof StudentMessagesConversationIdRouteImport
      parentRoute: typeof StudentMessagesRoute
    }
    '/student/results/$id': {
      id: '/student/results/$id'
      path: '/$id'
      fullPath: '/student/results/$id'
      preLoaderRoute: typeof StudentResultsIdRouteImport
      parentRoute: typeof StudentResultsRoute
    }
    '/student/user/$userId': {
      id: '/student/user/$userId'
      path: '/user/$userId'
      fullPath: '/student/user/$userId'
      preLoaderRoute: typeof StudentUserUserIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/super-admin/schools/': {
      id: '/super-admin/schools/'
      path: '/'
      fullPath: '/super-admin/schools/'
      preLoaderRoute: typeof SuperAdminSchoolsIndexRouteImport
      parentRoute: typeof SuperAdminSchoolsRoute
    }
    '/super-admin/schools/$id': {
      id: '/super-admin/schools/$id'
      path: '/$id'
      fullPath: '/super-admin/schools/$id'
      preLoaderRoute: typeof SuperAdminSchoolsIdRouteImport
      parentRoute: typeof SuperAdminSchoolsRoute
    }
    '/teacher/exam-paper/$id': {
      id: '/teacher/exam-paper/$id'
      path: '/exam-paper/$id'
      fullPath: '/teacher/exam-paper/$id'
      preLoaderRoute: typeof TeacherExamPaperIdRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCarryoversRoute: typeof AdminCarryoversRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminExaminationsRoute: typeof AdminExaminationsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminLevelsRoute: typeof AdminLevelsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOfficersRoute: typeof AdminOfficersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSemestersRoute: typeof AdminSemestersRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStructureRoute: typeof AdminStructureRoute
  AdminStudentImportRoute: typeof AdminStudentImportRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudentIdRoute: typeof AdminStudentIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCarryoversRoute: AdminCarryoversRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminExaminationsRoute: AdminExaminationsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminLevelsRoute: AdminLevelsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOfficersRoute: AdminOfficersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSemestersRoute: AdminSemestersRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStructureRoute: AdminStructureRoute,
  AdminStudentImportRoute: AdminStudentImportRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudentIdRoute: AdminStudentIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OfficerRouteChildren {
  OfficerApprovalsRoute: typeof OfficerApprovalsRoute
  OfficerAuditLogsRoute: typeof OfficerAuditLogsRoute
  OfficerCarryoversRoute: typeof OfficerCarryoversRoute
  OfficerIntegrityRoute: typeof OfficerIntegrityRoute
  OfficerLiveMonitorRoute: typeof OfficerLiveMonitorRoute
  OfficerNotificationsRoute: typeof OfficerNotificationsRoute
  OfficerPostToStudentsRoute: typeof OfficerPostToStudentsRoute
  OfficerProfileRoute: typeof OfficerProfileRoute
  OfficerReportsRoute: typeof OfficerReportsRoute
  OfficerResultsRoute: typeof OfficerResultsRoute
  OfficerSettingsRoute: typeof OfficerSettingsRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerExamPreviewIdRoute: typeof OfficerExamPreviewIdRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerApprovalsRoute: OfficerApprovalsRoute,
  OfficerAuditLogsRoute: OfficerAuditLogsRoute,
  OfficerCarryoversRoute: OfficerCarryoversRoute,
  OfficerIntegrityRoute: OfficerIntegrityRoute,
  OfficerLiveMonitorRoute: OfficerLiveMonitorRoute,
  OfficerNotificationsRoute: OfficerNotificationsRoute,
  OfficerPostToStudentsRoute: OfficerPostToStudentsRoute,
  OfficerProfileRoute: OfficerProfileRoute,
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerResultsRoute: OfficerResultsRoute,
  OfficerSettingsRoute: OfficerSettingsRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerExamPreviewIdRoute: OfficerExamPreviewIdRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface StudentMessagesRouteChildren {
  StudentMessagesConversationIdRoute: typeof StudentMessagesConversationIdRoute
}

const StudentMessagesRouteChildren: StudentMessagesRouteChildren = {
  StudentMessagesConversationIdRoute: StudentMessagesConversationIdRoute,
}

const StudentMessagesRouteWithChildren = StudentMessagesRoute._addFileChildren(
  StudentMessagesRouteChildren,
)

interface StudentResultsRouteChildren {
  StudentResultsIdRoute: typeof StudentResultsIdRoute
}

const StudentResultsRouteChildren: StudentResultsRouteChildren = {
  StudentResultsIdRoute: StudentResultsIdRoute,
}

const StudentResultsRouteWithChildren = StudentResultsRoute._addFileChildren(
  StudentResultsRouteChildren,
)

interface StudentRouteChildren {
  StudentContactOfficerRoute: typeof StudentContactOfficerRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentExaminationsRoute: typeof StudentExaminationsRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentMessagesRoute: typeof StudentMessagesRouteWithChildren
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentResultsRoute: typeof StudentResultsRouteWithChildren
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentExamIdRoute: typeof StudentExamIdRoute
  StudentUserUserIdRoute: typeof StudentUserUserIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentContactOfficerRoute: StudentContactOfficerRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentExaminationsRoute: StudentExaminationsRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentMessagesRoute: StudentMessagesRouteWithChildren,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentResultsRoute: StudentResultsRouteWithChildren,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentExamIdRoute: StudentExamIdRoute,
  StudentUserUserIdRoute: StudentUserUserIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperAdminSchoolsRouteChildren {
  SuperAdminSchoolsIdRoute: typeof SuperAdminSchoolsIdRoute
  SuperAdminSchoolsIndexRoute: typeof SuperAdminSchoolsIndexRoute
}

const SuperAdminSchoolsRouteChildren: SuperAdminSchoolsRouteChildren = {
  SuperAdminSchoolsIdRoute: SuperAdminSchoolsIdRoute,
  SuperAdminSchoolsIndexRoute: SuperAdminSchoolsIndexRoute,
}

const SuperAdminSchoolsRouteWithChildren =
  SuperAdminSchoolsRoute._addFileChildren(SuperAdminSchoolsRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminApplicationsRoute: typeof SuperAdminApplicationsRoute
  SuperAdminAuditLogsRoute: typeof SuperAdminAuditLogsRoute
  SuperAdminExaminationsRoute: typeof SuperAdminExaminationsRoute
  SuperAdminMessagesRoute: typeof SuperAdminMessagesRoute
  SuperAdminNotificationsRoute: typeof SuperAdminNotificationsRoute
  SuperAdminProfileRoute: typeof SuperAdminProfileRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminSchoolsRoute: typeof SuperAdminSchoolsRouteWithChildren
  SuperAdminServicesRoute: typeof SuperAdminServicesRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSubscriptionsRoute: typeof SuperAdminSubscriptionsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminApplicationsRoute: SuperAdminApplicationsRoute,
  SuperAdminAuditLogsRoute: SuperAdminAuditLogsRoute,
  SuperAdminExaminationsRoute: SuperAdminExaminationsRoute,
  SuperAdminMessagesRoute: SuperAdminMessagesRoute,
  SuperAdminNotificationsRoute: SuperAdminNotificationsRoute,
  SuperAdminProfileRoute: SuperAdminProfileRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminSchoolsRoute: SuperAdminSchoolsRouteWithChildren,
  SuperAdminServicesRoute: SuperAdminServicesRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSubscriptionsRoute: SuperAdminSubscriptionsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface TeacherRouteChildren {
  TeacherCoursesRoute: typeof TeacherCoursesRoute
  TeacherExamSecurityRoute: typeof TeacherExamSecurityRoute
  TeacherExaminationsRoute: typeof TeacherExaminationsRoute
  TeacherIntegrityRoute: typeof TeacherIntegrityRoute
  TeacherLiveExamsRoute: typeof TeacherLiveExamsRoute
  TeacherMarkingRoute: typeof TeacherMarkingRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherQuestionBankRoute: typeof TeacherQuestionBankRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherSubmissionsRoute: typeof TeacherSubmissionsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherExamPaperIdRoute: typeof TeacherExamPaperIdRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherCoursesRoute: TeacherCoursesRoute,
  TeacherExamSecurityRoute: TeacherExamSecurityRoute,
  TeacherExaminationsRoute: TeacherExaminationsRoute,
  TeacherIntegrityRoute: TeacherIntegrityRoute,
  TeacherLiveExamsRoute: TeacherLiveExamsRoute,
  TeacherMarkingRoute: TeacherMarkingRoute,
  TeacherMaterialsRoute: TeacherMaterialsRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherQuestionBankRoute: TeacherQuestionBankRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherSubmissionsRoute: TeacherSubmissionsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherExamPaperIdRoute: TeacherExamPaperIdRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplicationStatusRoute: ApplicationStatusRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotAppPasswordRoute: ForgotAppPasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationGalleryRoute: NotificationGalleryRoute,
  OfficerRoute: OfficerRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetAppPasswordRoute: ResetAppPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolApplicationRoute: SchoolApplicationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute: SupportRoute,
  TeacherRoute: TeacherRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
