// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

/** Public client keys for d4exam-platform (safe to embed in SPA). Used only if Vite env is blank. */
const FALLBACK_SUPABASE_URL = 'https://rqjchjytqcqjmljahcdr.supabase.co';
const FALLBACK_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxamNoanl0cWNxam1samFoY2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMjAwMzMsImV4cCI6MjEwMjU5NjAzM30.JWffmq5TIUnizWR-DIhwLylmHPmuuks2kUuEDEidlE8';
const FALLBACK_PUBLISHABLE_KEY = 'sb_publishable_VQOWXfgqJsrehi2sJGkdig_Gr8Zilr2';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const envUrl =
    (import.meta.env['VITE_SUPABASE_URL'] as string | undefined) ||
    (typeof process !== 'undefined' ? process.env?.['SUPABASE_URL'] : undefined) ||
    '';
  const envKey =
    (import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] as string | undefined) ||
    (import.meta.env['VITE_SUPABASE_ANON_KEY'] as string | undefined) ||
    (typeof process !== 'undefined'
      ? process.env?.['SUPABASE_PUBLISHABLE_KEY'] || process.env?.['SUPABASE_ANON_KEY']
      : undefined) ||
    '';

  // Prefer env; fall back to known d4exam-platform project so APK login never hits empty keys.
  const SUPABASE_URL = (envUrl && String(envUrl).trim()) || FALLBACK_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    (envKey && String(envKey).trim()) || FALLBACK_PUBLISHABLE_KEY || FALLBACK_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const message =
      'Missing Supabase environment variable(s). Connect Supabase in Lovable Cloud.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Prefer classic JWT anon key for Auth password grant compatibility in WebView.
  const authKey =
    (import.meta.env['VITE_SUPABASE_ANON_KEY'] as string | undefined) ||
    FALLBACK_SUPABASE_ANON_KEY ||
    SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, authKey, {
    global: {
      fetch: createSupabaseFetch(authKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
